---
deployment:
  tasks:
    - export DEPLOYPATH=~/public_html/smtp-artha.bhaktibuana.com/dist
    - if pgrep -f 'smtp-artha'; then pgrep -f 'smtp-artha' | xargs kill; fi
    - rm -rf $DEPLOYPATH/smtp-artha
    - rm -rf $DEPLOYPATH/assets
    - rsync -av --exclude '*.yml' --exclude '.*' ./ "$DEPLOYPATH"
    - chmod 0754 $DEPLOYPATH/smtp-artha
    - cd $DEPLOYPATH && nohup ./smtp-artha &
